{
 "title": "Dashboard General - Todas las máquinas",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Eficiencia Global",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "GLOBAL_EFFICIENCY_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Máquinas Activas",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "suffix: / 32" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "MACHINES_ACTIVE_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Tiempo de Parada Total",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "suffix: min" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "GLOBAL_DOWNTIME_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Eventos de Merma",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "GLOBAL_SCRAP_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Línea 1 · 13 máquinas · Minster · D&I · Printer · ISpray",
   "type": "row",
   "gridPos": { "x": 0, "y": 4, "w": 24, "h": 1 }
  },
  {
   "title": "Eficiencia Línea 1",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 5, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "LINE1_EFFICIENCY_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Producción por tipo · Línea 1",
   "type": "bargauge",
   "gridPos": { "x": 6, "y": 5, "w": 18, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "LINE1_MINSTER_PRODUCTION_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "LINE1_DI_PRODUCTION_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "LINE1_PRINTER_PRODUCTION_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "LINE1_ISPRAY_PRODUCTION_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Línea 3 · 19 máquinas · Minster · Standum · Printer · ISpray",
   "type": "row",
   "gridPos": { "x": 0, "y": 13, "w": 24, "h": 1 }
  },
  {
   "title": "Eficiencia Línea 3",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 14, "w": 6, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "LINE3_EFFICIENCY_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  },
  {
   "title": "Producción por tipo · Línea 3",
   "type": "bargauge",
   "gridPos": { "x": 6, "y": 14, "w": 18, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "LINE3_MINSTER_PRODUCTION_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "LINE3_STANDUM_PRODUCTION_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "LINE3_PRINTER_PRODUCTION_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    },
    {
     "aggregation": "average",
     "assetQuery": {
      "includeSubTimeseries": true,
      "includeSubtrees": false,
      "relationshipsQuery": {
       "dataSetIds": [],
       "depth": 1,
       "isActiveAtTime": false,
       "isTypeTimeseries": false,
       "labels": {
        "containsAny": []
       },
       "limit": 1000,
       "sourceExternalIds": []
      },
      "target": "",
      "withRelationships": false
     },
     "cogniteActivityQuery": {
      "enabled": false,
      "externalId": "CogniteActivity",
      "space": "cdf_cdm",
      "useScheduledTime": false,
      "version": "v1"
     },
     "cogniteActivityTabQuery": {
      "activeOnly": true,
      "assetInstances": [],
      "columns": [
       "externalId",
       "description",
       "startTime",
       "endTime"
      ],
      "externalId": "CogniteActivity",
      "instanceSpace": "",
      "resourceType": "CogniteAsset",
      "sort": [
       { "order": "asc", "property": "startTime" }
      ],
      "space": "cdf_cdm",
      "version": "v1"
     },
     "cogniteTimeSeries": { "externalId": "CogniteTimeSeries", "space": "cdf_cdm", "version": "v1" },
     "eventQuery": {
      "activeAtTimeRange": true,
      "advancedFilter": "",
      "aggregate": {
       "name": "uniqueValues",
       "properties": [],
       "withAggregate": false
      },
      "columns": [
       "externalId",
       "type",
       "subtype",
       "description",
       "startTime",
       "endTime"
      ],
      "expr": ""
     },
     "extractionPipelinesQuery": {
      "columns": [
       "name",
       "status",
       "lastUpdatedTime",
       "lastFailure",
       "lastSeen",
       "lastSuccess",
       "schedule",
       "data set",
       "message"
      ],
      "getRuns": false,
      "limit": 1000,
      "selections": []
     },
     "flexibleDataModellingQuery": {
      "externalId": "",
      "graphQlQuery": "{\n  listMachine {\n    items {\n      __typename\n      MachineWeight\n      Model\n      Anomalies {\n        externalId\n        id\n        name\n        __typename\n      }\n      Availability {\n        id\n        name\n        externalId\n        __typename\n      }\n    }\n  }\n}",
      "tsKeys": []
     },
     "relationshipsQuery": {
      "dataSetIds": [],
      "depth": 1,
      "isActiveAtTime": false,
      "isTypeTimeseries": false,
      "labels": {
       "containsAny": []
      },
      "limit": 1000,
      "sourceExternalIds": []
     },
     "tab": "Timeseries",
     "target": "LINE3_ISPRAY_PRODUCTION_SHIFT",
     "targetRefType": "externalId",
     "templateQuery": {
      "dataPath": "oEE_MachinesQuery.items",
      "datapointsPath": "GoodQuantity.datapoints",
      "graphQlQuery": "{\n  oEE_MachinesQuery {\n    items {\n      Facility\n      Line\n      GoodQuantity {\n        datapoints (start: $__from, end: $__to, , limit: 100){\n            value\n            timestamp\n        }\n      }\n    }\n  }\n}",
      "groupBy": "Facility"
     }
    }
   ]
  }
 ]
}